FROM eclipse-temurin:17-jdk-jammy AS builder
WORKDIR /app
COPY . .
RUN ./mvnw clean install -DskipTests

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /app/web/target/web-1.0-SNAPSHOT.jar app.jar
EXPOSE 8080
EXPOSE 9000
ENTRYPOINT ["java", "-jar", "app.jar"]
